<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.5.0" /><PackageReference Include="Azure.Identity" Version="1.*" /><PackageReference Include="CommunityToolkit.VectorData.AzureCosmosDB" Version="*" /><PackageReference Include="Microsoft.Azure.Cosmos" Version="3.*" /><PackageReference Include="Newtonsoft.Json" Version="13.*" />
  </ItemGroup>
</Project>
